### ISSUE TITLE
Would you be willing to transfer ownership of Vente?

### ISSUE THREAD

**Issue by pmccarren** [Vente/VenteStudiosWebsite#1]
Hello!

I am in the process of bootstrapping a new startup and am working on an MVP concept. I was wondering if your organization name "Vente" is currently being used? If not, would you be interested in transferring me ownership?

Thank you!
Patrick

**Comment by FoxyDysphoria** [comment]
While it isn't currently in use, Vente, as a concept, is something very
important to me. Its kind of hard to explain, but I'm more than likely not
willing to part with the name.

That being said, if you can explain why the name Vente is important to you,
your project, or your startup, and it's a valid and compelling reason, I'll
consider it.

Like I said, it's a name with history and meaning to me. I'm not trying to
be rude. I hope you understand.

Thanks,
Clayton White

**Comment by pmccarren** [comment]
I most certainly understand that you have a personal attachment to the name, and I absolutely understand your desire to hang on to it! 

I spent the past 8 months building a Restaurant Point of Sale system and am nearing a beta. During this time I too developed an attachment to the name 'Vente' and was drawn to this name in particular because of its etymology which stems from the 'act of selling'.

I would greatly appreciate you considering to transfer the name, and of course no hard feelings either way! :)

Thanks again,
Patrick
